(* block comment *) (* multiline 
block comment *)
PROGRAM blockComments(* block comment *) (* multiline 
block comment *) 
    VAR (* block comment *) (* multiline 
block comment *)
		a : INT;(* block comment *) (* multiline   
block comment *)
    END_VAR(* block comment *) (* multiline 
block comment *) 
		a (* block comment *) :=  (* block comment *) 1;(* block comment *) (* multiline 
block comment *)
    b := 5;(* block comment *) (* multiline 
block comment *)
END_PROGRAM(* block comment *) (* multiline 
block comment *)  
(* block comment *) (* multiline 
block comment *)