name: Build and test

on:
  push:
    paths:
      - 'st_interpret/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./st_interpret
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-c
        version: latest
        use-tool-cache: true
    - name: pre-build clean
      run: ./clean.sh
    - name: build project
      run: ./build.sh
    - name: run tests
      run: ./test.sh
    - name: post-build clean
      run: ./clean.sh
